application: silly-chess
version: alpha-002
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /js
  static_dir: static/js

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /
  static_files: static/overview.html
  upload: static/overview.html
  login: required

- url: /board
  static_files: static/board.html
  upload: static/board.html
  login: required

- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  script: api.app
  login: required
